/**
 * Generate the desktop application's runtime deploy root.
 *
 * `pnpm deploy` materializes exactly what the deploy root's manifest declares:
 * peers are not installed automatically, and a workspace package reached only
 * through the `link:` overrides in pnpm-workspace.yaml is skipped unless the
 * root names it. Listing every reachable workspace package makes both cases
 * impossible, and generating that list keeps it correct as the CLI's graph
 * changes.
 *
 * Run: `pnpm run gen-desktop-runtime-closure` (add `--check` to fail instead of write).
 */

import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { parseArgs } from 'node:util'
import { loadWorkspacePackages, walkClosure } from './workspace-closure.ts'

const root = resolve(import.meta.dirname, '..')

/** The generated manifest. */
const MANIFEST_PATH = 'apps/desktop/runtime/package.json'

/** The application whose closure the desktop runtime ships. */
const SEED_PACKAGE = '@deepseek-ai/dsh'

/** Manifest globs covering every workspace member a deploy root can reach, including the seed app. */
const WORKSPACE_GLOBS = [
  'packages/*/*/package.json',
  'vendor/*/package.json',
  'apps/*/package.json',
]

/** Fields the generated manifest carries besides its dependencies. */
const MANIFEST_HEADER = {
  name: 'dsh-desktop-runtime-pkg',
  description: 'Dependency-only deploy root for the desktop application\'s embedded harness runtime; generated by scripts/gen-desktop-runtime-closure.ts.',
  version: '0.0.1',
  private: true,
  type: 'module',
} as const

/**
 * Compose the manifest text for the current workspace graph.
 * @returns the manifest as it should exist on disk, newline-terminated.
 */
async function renderManifest(): Promise<string> {
  const workspace = await loadWorkspacePackages(root, WORKSPACE_GLOBS)
  if (!workspace.has(SEED_PACKAGE)) {
    throw new Error(`gen-desktop-runtime-closure: ${SEED_PACKAGE} is not a workspace member.`)
  }
  const walk = walkClosure(workspace, { [SEED_PACKAGE]: 'workspace:^' }, { followPeers: true })
  const dependencies: Record<string, string> = {}
  for (const name of [...walk.order].sort()) dependencies[name] = 'workspace:^'
  return `${JSON.stringify({ ...MANIFEST_HEADER, dependencies }, undefined, 2)}\n`
}

const { values } = parseArgs({ args: process.argv.slice(2), options: { check: { type: 'boolean', default: false } } })
const target = resolve(root, MANIFEST_PATH)
const rendered = await renderManifest()

if (!values.check) {
  await writeFile(target, rendered)
  console.log(`gen-desktop-runtime-closure: wrote ${MANIFEST_PATH}`)
} else {
  let current: string
  try {
    current = await readFile(target, 'utf8')
  } catch {
    // An absent manifest is as stale as a wrong one, and reports the same fix.
    current = ''
  }
  if (current !== rendered) {
    console.error(`gen-desktop-runtime-closure: ${MANIFEST_PATH} is stale; run 'pnpm run gen-desktop-runtime-closure' and 'pnpm install'.`)
    process.exit(1)
  }
  console.log(`gen-desktop-runtime-closure: ${MANIFEST_PATH} is current.`)
}
